name: python_dvr
channels:
  - conda-forge
dependencies:
  - appnope=0.1.3
  - asttokens=2.0.5
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cycler=0.11.0
  - decorator=5.1.1
  - executing=0.8.3
  - fonttools=4.32.0
  - freetype=2.10.4
  - giflib=5.2.1
  - ipdb=0.13.9
  - ipython=8.2.0
  - jbig=2.1
  - jedi=0.18.1
  - jpeg=9e
  - kiwisolver=1.4.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=13.0.1
  - libdeflate=1.10
  - libffi=3.4.2
  - libgfortran
  - libgfortran5
  - liblapack=3.9.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libtiff=4.3.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.11
  - llvm-openmp=13.0.1
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - munkres=1.1.4
  - ncurses=6.3
  - numpy=1.22.3
  - openjpeg=2.4.0
  - openssl=3.0.2
  - packaging=21.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.1.0
  - pip=22.0.4
  - prompt-toolkit=3.0.29
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - pyparsing=3.0.8
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - readline=8.1
  - scipy=1.8.0
  - setuptools=62.1.0
  - six=1.16.0
  - sqlite=3.38.2
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.1.1
  - unicodedata2=14.0.0
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yapf=0.32.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
      - pyvoro==1.3.2
      - tsp-solver2==0.4.1
